### ISSUE TITLE
update terraform version and code to 1.14 (latest)

### ISSUE THREAD

**Issue by michalbagrowski** [aeternity/terraform-aws-misc#9]

**Comment by michalbagrowski** [comment]
@dincho can yo please take a look https://app.circleci.com/pipelines/github/aeternity/terraform-aws-misc/20/workflows/10bd79d4-ddfe-4073-abe7-3f8f6b7bf561/jobs/31/parallel-runs/0/steps/0-106 it looks like some "manual" changes on AWS, how proceed with this?

**Comment by michalbagrowski** [comment]
@dincho do we care about this repo?

**Comment by dincho** [comment]
We do, I've to check in details
